Some Reinforcement learning example problems present in the GYM library.

# Creating a CartPole Environment

In [1]:
%load_ext tensorboard
import gym
env = gym.make('CartPole-v0')
print(env)
env.reset()
for _ in range(200):
    env.render()
    env.step(env.action_space.sample())
env.close()

<TimeLimit<CartPoleEnv<CartPole-v0>>>


c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\gym\logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


# Creating a MountainCar Environment

In [2]:
%load_ext tensorboard
import gym
env = gym.make('MountainCar-v0')
print(env)
env.reset()
for _ in range(300):
    env.render()
    env.step(env.action_space.sample())
env.close()

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
<TimeLimit<MountainCarEnv<MountainCar-v0>>>


# Creating a Pendulum Environment

In [3]:
import gym
env = gym.make('Pendulum-v0')
print(env)
env.reset()
for _ in range(250):
    env.render()
    env.step(env.action_space.sample())
env.close()

<TimeLimit<PendulumEnv<Pendulum-v0>>>


# Printing The Probability of observation, reward, state and Action

In [5]:
%load_ext tensorboard
import gym
env = gym.make('CartPole-v0')
env.reset()
for i_episode in range(10):
    observation = i_episode
    for t in range(10):
        env.render()
        action = env.action_space.sample()
        observation, state, reward, action = env.step(action)
        print(observation, state, reward, action)
env.close()

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
[ 0.01119489  0.24377579  0.00750773 -0.30577477] 1.0 False {}
[ 0.01607041  0.43878996  0.00139223 -0.59608052] 1.0 False {}
[ 0.02484621  0.24364855 -0.01052938 -0.30295937] 1.0 False {}
[ 0.02971918  0.04867823 -0.01658857 -0.01361569] 1.0 False {}
[ 0.03069274  0.24403411 -0.01686088 -0.311486  ] 1.0 False {}
[ 0.03557343  0.04915638 -0.0230906  -0.02416782] 1.0 False {}
[ 0.03655655 -0.14562695 -0.02357396  0.26114126] 1.0 False {}
[ 0.03364401 -0.34040459 -0.01835113  0.54629644] 1.0 False {}
[ 0.02683592 -0.53526396 -0.0074252   0.83314135] 1.0 False {}
[ 0.01613064 -0.34004134  0.00923762  0.5381325 ] 1.0 False {}
[ 0.00932982 -0.53529194  0.02000027  0.83371172] 1.0 False {}
[-0.00137602 -0.73068137  0.03667451  1.13261694] 1.0 False {}
[-0.01598965 -0.53605817  0.05932685  0.85165833] 1.0 False {}
[-0.02671081 -0.34179307  0.07636001  0.57820521] 1.0 False {}
[-0.03354667 -0.5378975   0.

Similarly For MountainCar and Pendulum Problem

In [9]:
%load_ext tensorboard
import gym
env = gym.make('MountainCar-v0')
env.reset()
for i_episode in range(15):
    observation = i_episode
    for t in range(10):
        env.render()
        action = env.action_space.sample()
        observation, state, reward, action = env.step(action)
        print(observation, state, reward, action)
env.close()

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
[-0.41347773 -0.00081676] -1.0 False {}
[-0.41610545 -0.00262772] -1.0 False {}
[-0.42052548 -0.00442002] -1.0 False {}
[-0.42670629 -0.00618081] -1.0 False {}
[-0.4346036  -0.00789732] -1.0 False {}
[-0.44316048 -0.00855688] -1.0 False {}
[-0.45131481 -0.00815433] -1.0 False {}
[-0.46000703 -0.00869222] -1.0 False {}
[-0.4701733  -0.01016627] -1.0 False {}
[-0.48073855 -0.01056525] -1.0 False {}
[-0.49062436 -0.00988581] -1.0 False {}
[-0.49975708 -0.00913272] -1.0 False {}
[-0.50906846 -0.00931138] -1.0 False {}
[-0.51748878 -0.00842032] -1.0 False {}
[-0.52495492 -0.00746614] -1.0 False {}
[-0.53141089 -0.00645597] -1.0 False {}
[-0.53880828 -0.00739739] -1.0 False {}
[-0.54509164 -0.00628336] -1.0 False {}
[-0.55221391 -0.00712227] -1.0 False {}
[-0.55812183 -0.00590792] -1.0 False {}
[-0.56477129 -0.00664946] -1.0 False {}
[-0.57011274 -0.00534145] -1.0 False {}
[-0.57510647 -0.00499373] -1.0

In [10]:
%load_ext tensorboard
import gym
env = gym.make('Pendulum-v0')
env.reset()
for i_episode in range(15):
    observation = i_episode
    for t in range(10):
        env.render()
        action = env.action_space.sample()
        observation, state, reward, action = env.step(action)
        print(observation, state, reward, action)
env.close()

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
[-0.9997074   0.02418917  0.35270007] -9.621971204339676 False {}
[-0.99995368  0.00962446  0.2913384 ] -9.730910416388411 False {}
[-0.99997803 -0.00662888  0.32507078] -9.817742867318382 False {}
[-0.99993662 -0.01125844  0.09259499] -9.840865027012082 False {}
[-0.99996418 -0.00846415 -0.05588857] -9.800719795088916 False {}
[-0.99998413 -0.00563304 -0.05662361] -9.816807358673563 False {}
[-0.99990814 -0.0135543   0.15843294] -9.836700228928368 False {}
[-0.99936821 -0.0355413   0.4398814 ] -9.790910950522456 False {}
[-0.99753253 -0.07020577  0.69429572] -9.670369214000731 False {}
[-0.99409658 -0.10849881  0.76898506] -9.481987719969307 False {}
[-0.98824253 -0.1528944   0.89567246] -9.25941784795418 False {}
[-0.98241385 -0.18671645  0.68644602] -9.009339226689235 False {}
[-0.97688453 -0.21376768  0.55222865] -8.771902608412509 False {}
[-0.97544018 -0.22026451  0.13310906] -8.595899102866

# Printing all the Example's The examples Present in the gym library

In [11]:
from gym import envs
print(envs.registry.all())

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v2), EnvSpec(BipedalWalkerHardcore-v2), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v0), EnvSpec(FrozenLake8x8-v0), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v3), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(HalfCheetah-v3), EnvSpec(Hopper-v2), EnvSpec(Hopper-v3), EnvSpec(Swimmer-v2), EnvSp

# Implementation of Self Driving Cab using Reinforcement Learning

In [1]:
import gym
env = gym.make('Taxi-v3')


In [2]:
print(env)
env.reset()

<TimeLimit<TaxiEnv<Taxi-v3>>>


361

In [3]:
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [4]:
env.reset()
env.render()

print('Action_State {}'.format(env.action_space))
print('Observation_sate {}'.format(env.observation_space))

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

Action_State Discrete(6)
Observation_sate Discrete(500)


In [5]:
state = env.encode(3, 1, 2, 0)     #current location of the cab
print(state)

328


In [6]:
env.s = state  #current state of the cab
env.s

328

In [7]:
env.render()   #will print the simulation of the present state in which a car is present

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [8]:
env.P[328]    #initial reward table

{0: [(1.0, 428, -1, False)],
 1: [(1.0, 228, -1, False)],
 2: [(1.0, 348, -1, False)],
 3: [(1.0, 328, -1, False)],
 4: [(1.0, 328, -10, False)],
 5: [(1.0, 328, -10, False)]}

In [ ]:
env.s = 328

epchos = 0
penalties = 0
reward = 0

frames = []

done = False
while not done:
    env.render()
    action = env.action_space.sample()
    observation, state, reward, action = env.step(action)
    #print(observation, state, reward, action)
    
    if reward == -10:
        penalties += 1
    
    epchos += 1
print('Timesteps Taken {}'.format(epchos))
print('Penalties Incurred {}'.format(penalties))

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : |

# Q-Learning

In [9]:
import numpy as np
q_table = np.zeros([env.observation_space.n, env.action_space.n])
q_table

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
q_table.shape

(500, 6)

In [11]:
alpha = 0.7
gamma = 0.6
epsilon = 0.1

In [12]:
import numpy as np
import random
from IPython.display import clear_output
from time import sleep
import seaborn as sn
import matplotlib.pyplot as plt

In [ ]:
# For plotting metrics
all_epochs = []
all_penalties = []

for i in range(1, 100001):
    state = env.reset()

    epochs, penalties, reward, = 0, 0, 0
    done = False
    
    while not done:
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(q_table[state]) # Exploit learned values

        next_state, reward, done, info = env.step(action) 
        
        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value

        if reward == -10:
            penalties += 1

        state = next_state
        epochs += 1
        
    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")

print("Training finished.\n")

In [ ]:
q_table[328]

In [ ]:
all_epchos = 0
all_prnalties = 0
episodes = 100

for i in range(episodes):
    reward, penalties, epchos = 0, 0, 0
    
    done = False
    
    while not done:
        action = np.argmax(q_table[state])
        state, reward, info, done = env.step(action)
        
        if reward == -10:
            penalties += 1
            
        epchos += 1
        total_penalties += penalties
        total_epchos += epchos
print(f"results after {episode} episodes")
print("average timestep per episode", total_epchos/episodes)
print("average penalties per episode", total_penalties/episodes)

# Frozen Lake Problem

In [16]:
import gym
env = gym.make('FrozenLake-v0')
print(env)

<TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>


In [17]:
state = print('Observation State ', env.observation_space)
print('action_state', env.action_space)

Observation State  Discrete(16)
action_state Discrete(4)


In [35]:
qtable = np.zeros([env.observation_space.n, env.action_space.n])
qtable

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
print(env.P)

{0: {0: [(0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 4, 0.0, False)], 1: [(0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 4, 0.0, False), (0.3333333333333333, 1, 0.0, False)], 2: [(0.3333333333333333, 4, 0.0, False), (0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False)], 3: [(0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 0, 0.0, False)]}, 1: {0: [(0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 5, 0.0, True)], 1: [(0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 2, 0.0, False)], 2: [(0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 2, 0.0, False), (0.3333333333333333, 1, 0.0, False)], 3: [(0.3333333333333333, 2, 0.0, False), (0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False)]}, 2: {0: [(0.3333333333333333, 2, 0.0, False), (0.3333333333333333

In [37]:
total_episodes = 20000       # Total episodes
learning_rate = 0.7          # Learning rate
max_steps = 99               # Max steps per episode
gamma = 0.95                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005            # Exponential decay rate for exploration prob

In [38]:
# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
            #print(exp_exp_tradeoff, "action", action)

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()
            #print("action random", action)
            
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
       # print(qtable)
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)
    

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
env.reset()

for episode in range(10):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            if new_state == 15:
                print("We reached our Goal 🏆")
            else:
                print("We fell into a hole ☠️")
            
            # We print the number of step it took.
            print("Number of steps", step)
            
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 2
****************************************************
EPISODE  1
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 18
****************************************************
EPISODE  2
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 10
****************************************************
EPISODE  3
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 5
****************************************************
EPISODE  4
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 41
****************************************************
EPISODE  5
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 11
****************************************************
EPISODE  6
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 13
****************************************************
EPIS